--- #################### 数据库相关配置 ####################
spring:
  mail:
    # 平台地址， QQ邮箱
    host: smtp.qq.com
    username: 153640709@qq.com
    password: kvphukjeomntbiif
    default-encoding: UTF-8
    test-connection: true

  # 数据源配置项
  datasource:
    name: hbTest
    url: jdbc:mysql://10.10.55.134:3306/${spring.datasource.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  custom:
    ipAddress: ipAddress
    outTime: outTime
    verifyCode: verifyCode
    emailStr: emailStr

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 86400
  # 多端不同 token 有效期 可查看 LoginHelper.loginByDevice 方法自定义
  # token最低活跃时间 (指定时间无操作就过期) 单位: 秒
  active-timeout: 1800
  # 允许动态设置 token 有效期
  dynamic-active-timeout: true
  # 开启内网服务调用鉴权
  check-same-token: false
  # Same-Token的有效期 (单位: 秒)(默认一天）
  # same-token-timeout: 600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  token-prefix: "Bearer"
  # jwt秘钥
  jwt-secret-key: resouce-exchange@com.bill

--- #####白名单配置######
# 不校验白名单
security:
  ignore:
    whites:
      - /*/admin/getVerifyCode

server:
  servlet:
    session:
      persistent: false